# Docker Compose for Development Environment
# Only runs infrastructure (PostgreSQL, Redis, Traefik)
# Services (auth, post) run locally on host machine

services:
  # Traefik API Gateway (replaces Traefik)
  traefik:
    image: traefik:v3.0
    container_name: bw-traefik-dev
    restart: unless-stopped
    ports:
      - "8000:8000"    # HTTP API - same as Traefik
      - "8080:8080"    # Dashboard (dev only)
    volumes:
      - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic-config.dev.yml:/etc/traefik/dynamic/config.yml:ro
    networks:
      - bw-network
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bw-postgres-dev
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: master123
      POSTGRES_DB: postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./migrations/init-schemas.sql:/docker-entrypoint-initdb.d/01-init-schemas.sql:ro
    networks:
      - bw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: bw-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_dev_data:/data
    networks:
      - bw-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  dufs-service:
      container_name: bw-dufs-service
      restart: unless-stopped
      # Sử dụng 'build' thay cho 'image'
      build:
        context: ./dms/dufs  # Đường dẫn đến thư mục chứa Dockerfile
        dockerfile: Dockerfile # Tên của Dockerfile
      command: ["/data", "-p", "5000", "--allow-all"]
      volumes:
        - ./managed_files:/data  # Ánh xạ thư mục local vào container
      networks:
        - bw-network
      # Chỉ expose port cho mạng nội bộ, không mở ra ngoài
      expose:
        - "5000"
      healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/__dufs__/health || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3

  # k6 Load Testing Service
  k6-tests:
    build:
      context: ./k6-tests
      dockerfile: Dockerfile
    container_name: bw-k6-tests-dev
    environment:
      MODE: dev
    networks:
      - bw-network
    depends_on:
      - traefik
      - postgres
      - redis
    profiles:
      - test

networks:
  bw-network:
    driver: bridge

volumes:
  postgres_dev_data:
  redis_dev_data:

