_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://host.docker.internal:3001
    routes:
      - name: auth-routes
        paths:
          - /auth
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
      - name: partner-routes
        paths:
          - /v1/partner
        strip_path: false
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
      - name: user-routes
        paths:
          - /v1/user
        strip_path: false
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE

  - name: post-service
    url: http://host.docker.internal:3002
    routes:
      - name: post-routes
        paths:
          - /post
        strip_path: true
        preserve_host: false
        protocols:
          - http
          - https
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
    # 3. (Mới) Thêm dufs-service
  - name: dufs-service
    url: http://dufs-service:5000
    routes:
      - name: dufs-routes
        paths:
          - /files
        strip_path: true # Xóa /files khỏi path trước khi gửi đến dufs
        plugins:
          # 4. (Mới) Áp dụng plugin JWT cho route này
          - name: jwt

# 1. (Mới) Tạo một consumer đại diện cho người dùng của hệ thống
consumers:
  - username: system-user

# 2. (Mới) Đăng ký JWT secret cho consumer trên
# Kong sẽ dùng secret này để xác thực token
jwt_secrets:
  - consumer: system-user
    key: "backend-works-app"
    # Sửa lại thành tên biến đúng mà Docker Compose đã truyền vào
    secret: "EAJYjNJUnRGJ6uq1YfGw4NG1pd1z102J"
    algorithm: HS256
# Kong configuration for development
# Services run on host machine (host.docker.internal)          

plugins:
  - name: rate-limiting
    route: auth-routes
    config:
      minute: 100
      hour: 1000
      day: 10000
      policy: local
      hide_client_headers: false
      fault_tolerant: true

  - name: rate-limiting
    route: post-routes
    config:
      minute: 200
      hour: 2000
      day: 20000
      policy: local
      hide_client_headers: false
      fault_tolerant: true

  - name: rate-limiting
    route: partner-routes
    config:
      minute: 50
      hour: 500
      day: 5000
      policy: local
      hide_client_headers: false
      fault_tolerant: true

  - name: rate-limiting
    config:
      minute: 300
      hour: 3000
      day: 30000
      policy: local
      hide_client_headers: false
      fault_tolerant: true

